Aplicaciones/Modulo/urls.py
from django.urls import path
from .views import booksPage, bookDetail, bookRequest, adminView, adminBookDetail, adminDeleteBook, adminAddBook, adminRequestList, LogInUser
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login

app_name='modulo'
urlpatterns = [
    path('', login_required(booksPage), name='BooksPage'),
    path('BookDetail/<id>',bookDetail, name='BookDetail'),
    path('BookRequest/<id>', bookRequest, name='BookRequest'),
    path('AdminBooksPage/', views.adminView, name='AdminBooksPage'),
    path('AdminBookDetail/<id>/', adminBookDetail, name='AdminBookDetail'),
    path('AdminDeleteBook/<id>/',adminDeleteBook, name='AdminDeleteBook'),
    path('AdminAddBook/', adminAddBook, name='AdminAddBook'),
    path('AdminRequestList/', adminRequestList, name='AdminRequestList'),
] 

BibliotecaPolitecnica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login
from Aplicaciones.Modulo.views import LogInUser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Aplicaciones.Modulo.urls')),
    path('accounts/login/', LogInUser, name = 'login'),
    path('Logout/', logout_then_login, name='logout')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicaciones/Modulo/models.py
from django.core.validators import MaxValueValidator, MinValueValidator 
from django.core.files.storage import default_storage
from django.db import models

class Carrera(models.Model):
    id_carrera = models.BigAutoField(primary_key=True)
    nom_carrera = models.CharField(max_length=50)

    def __str__(self):
        return str(self.nom_carrera)
    
class Cargo (models.Model):
    id_cargo= models.BigAutoField(primary_key=True)
    nombre= models.CharField(max_length=20)
    def __str__(self):
        return str(self.nombre)
    
class Turno(models.Model):
    id_turno = models.BigAutoField(primary_key=True)
    nom_turno = models.CharField(max_length=30)
    def __str__(self):
        return str(self.nom_turno)

class Libro(models.Model):
    codigo_interno = models.IntegerField(primary_key=True)
    titulo = models.CharField(max_length=50)
    autor = models.CharField(max_length=50)
    disponibles = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])
    estado_libro = models.CharField(max_length=50)
    idioma = models.CharField(max_length=30)
    editorial = models.CharField(max_length=50)
    paginas = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(3000)])
    imagen = models.ImageField(upload_to='media/images', storage=default_storage)
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.titulo}'
    
    class Meta:
        ordering = ['codigo_interno']

class Usuario(models.Model):
    id_usuario = models.BigAutoField(primary_key=True)
    nombre_completo = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    contraseña = models.CharField(max_length=50)
    id_cargo= models.ForeignKey(Cargo, on_delete=models.CASCADE)
    id_turno = models.ForeignKey(Turno, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nombre_completo} - {self.id_cargo.nombre}'

class Prestamo(models.Model):
    id_prestamo = models.BigAutoField(primary_key=True)
    fecha_prestamo = models.DateField()
    fecha_devolucion = models.DateField()
    id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id_usuario.nombre_completo} - {self.id_prestamo}'

class Det_Prestamo(models.Model):
    id_det_prestamo = models.BigAutoField(primary_key=True)
    cant_libros = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(3)])
    estatus = models.CharField(max_length=50)
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE, null=True)
    id_prestamo = models.ForeignKey(Prestamo, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id_prestamo.id_usuario.nombre_completo} - {self.id_prestamo.id_prestamo}'

""" class Librero(models.Model):
    id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    activo = models.BooleanField(default=False)

    def get_librero_total(self):
        libros = self.librero_items.all()
        print(libros)

class Det_Librero(models.Model):
    librero = models.ForeignKey(Librero, on_delete=models.CASCADE)
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE) """

Aplicaciones/Modulo/forms.py
from django import forms
from .models import Usuario, Libro, Prestamo, Cargo, Carrera, Turno

class ChargeForm(forms.ModelForm):
    
    class Meta:
        model = Cargo
        fields = '__all__'

class CareerForm(forms.ModelForm):
    
    class Meta:
        model = Carrera
        fields = '__all__'

class ShiftForm(forms.ModelForm):
    
    class Meta:
        model = Turno
        fields = '__all__'

class UserForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = '__all__'

class BookForm(forms.ModelForm):

    class Meta:
        model = Libro
        fields = '__all__'

class RequestForm(forms.ModelForm):

    class Meta:
        model = Prestamo
        fields = '__all__'

Aplicaciones/Modulo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.db.models import Q
from datetime import date, timedelta
from .forms import *
from .models import *

def LogInUser(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_staff:
                login(request, user)
                return redirect('modulo:AdminBooksPage')
            else:
                login(request, user)
                return redirect('modulo:BooksPage')
        else:
            messages.success(request, 'Usuario o contraseña incorrectos')

    return render(request, "logIn.html")

def LogOutUser(request):
    logout(request)
    return redirect('modulo:logInUser')


def booksPage(request):
    libros = Libro.objects.all()
    carreras = Carrera.objects.all()
    user = request.user
    busqueda = request.GET.get("buscar")

    """Verificar si el usuario es administrador o alumno"""
    """ if user.is_staff:
        usuario = user
    else:
        usuario = get_object_or_404(Usuario, email = request.user.username) """

    """Realizar busqueda de libro"""
    if busqueda:
        libros = Libro.objects.filter(
            Q(codigo_interno__icontains = busqueda) |
            Q(titulo__icontains = busqueda) |
            Q(autor__icontains = busqueda) |
            Q(idioma__icontains = busqueda)
        ).distinct()

        carreras = []
        for libro in libros:    
            carrera = libro.carrera
            if carrera is not None:
                carreras.append(carrera)

    data = {
        'libros': libros,
        'carreras': carreras,
        # 'usuario': usuario,
    }

    return render(request, "paginaLibros.html", data)


def bookDetail(request, id):
    book = get_object_or_404(Libro, codigo_interno = id)
    data = {
        'book': book
    }
    return render(request, "bookDetail.html", data)

def bookRequest(request, id):
    """Crear Prestamo"""
    request_date = date.today()
    return_request_date = request_date + timedelta(3)
    request_user = get_object_or_404(Usuario, email = request.user.username)
    book_request = Prestamo.objects.create(fecha_prestamo=request_date, fecha_devolucion=return_request_date, id_usuario=request_user)
    """Crear detalle Prestamo"""
    libro = Libro.objects.get(codigo_interno = id)
    det_prestamo = Det_Prestamo.objects.create(cant_libros = 1, estatus =  "Prestamo", libro = libro, id_prestamo = book_request)
    det_prestamo.save()
    data = {
        'book_request': book_request,
        'request_book_user': UserForm(instance=request_user)
    }

    return render(request, "bookRequest.html", data)

def adminView(request):
    libros = Libro.objects.all()
    carreras = Carrera.objects.all()

    data = {
        'libros': libros,
        'carreras': carreras,
        'user_form': UserForm(),
        'charge_form': ChargeForm(),
        'career_form': CareerForm(),
        'shift_form': ShiftForm()
    }

    """Registro de Usuario"""
    if request.method == 'POST':
        """Añadir Usuario"""
        user_form = UserForm(data=request.POST)
        username = request.POST.get('email')
        email = request.POST.get('email')
        password  = request.POST.get('contraseña')
        if user_form.is_valid():
            user_form.save()
            new_user = User.objects.create_user(username, email, password)
            new_user.save()
            messages.success(request, 'Usuario registrado correctamente')
        else:
            data['user_form'] = user_form

        """Añadir Carrera"""
        career_form = CareerForm(data=request.POST)
        if career_form.is_valid():
            career_form.save()
            messages.success(request, 'Carrera creada correctamente')
        else:
            data['career_form'] = career_form

        """Añadir Cargo"""
        charge_form = ChargeForm(data=request.POST)
        if charge_form.is_valid():
            charge_form.save()
            messages.success(request, 'Cargo creado correctamente')
        else:
            data['charge_form'] = charge_form

        """Añadir Turno"""
        shift_form = ShiftForm(data=request.POST)
        if shift_form.is_valid():
            shift_form.save()
            messages.success(request, 'Turno creado correctamente')
        else:
            data['shift_form'] = shift_form
        
    return render(request, "adminBooksPage.html", data)


def adminBookDetail(request, id):
    libro = get_object_or_404(Libro, codigo_interno = id)
    data = {
        'book_form': BookForm(instance=libro),
        'book': libro
    }
    if request.method == 'POST':
        book_form = BookForm(data=request.POST, instance=libro, files=request.FILES)
        if book_form.is_valid():
            book_form.save()
            messages.success(request, 'Libro guardado correctamente')
            return redirect("modulo:AdminBooksPage")
        else:
            data['book_form'] = book_form
    return render(request, "adminBookDetail.html", data)


def adminAddBook(request):
    data = {
        'book_form': BookForm()
    }
    if request.method == 'POST':
        book_form = BookForm(data=request.POST, files=request.FILES)
        if book_form.is_valid():
            book_form.save()
            messages.success(request, 'Libro agregado correctamente')
            return redirect("modulo:AdminBooksPage")
        else:
            data['book_form'] = book_form
    return render(request, "adminAddBook.html", data)


def adminDeleteBook(request, id):
    libro = get_object_or_404(Libro, codigo_interno = id)
    libro.delete()
    messages.success(request, 'Libro eliminado correctamente')
    return redirect(to="modulo:AdminBooksPage")


def adminRequestList(request):
    prestamos = Prestamo.objects.all()
    det_prestamos = Det_Prestamo.objects.all()
    busqueda = request.GET.get("buscar")

    """Realizar busqueda de prestamo"""
    if busqueda:
        prestamos = Prestamo.objects.filter(
            Q(id_prestamo__icontains = busqueda) |
            Q(id_usuario__nombre_completo__icontains = busqueda) 
        ).distinct()

    data = {
        "prestamos":prestamos,
        "det_prestamos": det_prestamos,
    }
    return render(request, "adminRequestList.html", data)

""" def addToBookCart(request, id):
    libro = Libro.objects.get(codigo_interno = id)
    user = get_object_or_404(Usuario, email = request.user.username)
    librero , _ = Librero.objects.get_or_create(id_usuario = user, activo = False)

    det_librero = Det_Librero.objects.create(librero = librero, libro = libro)
    det_librero.save()

    return redirect("modulo:BooksPage")

def deleteBookInBookCart(request, id):
    try:
        libro = Det_Librero.objects.get(libro = id)
        libro.delete()
    except Exception as e:
        print(e)


def BookCart(request):
    data = {
        'context': context
        }
    context = {'librero' : Librero.objects.filter(activo = False, id_usuario = request.user)} """

Aplicaciones/Modulo/templates/BarraNavegacionPrincipal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<body>
    <nav class="navbar navbar-expand-lg">

        <div class="navbar-left">

            <div class="navbar-logo">
                <a href="{% url 'modulo:BooksPage' %}">
                    <img src="{%static 'images/LogoUPTap.png'%}" alt="Logo">
                </a>
            </div>

            <div class="navbar-titulo">
                <p>Biblioteca Politécnica</p>
            </div>

        </div>

        <div class="navbar-search">

            <div class="navbar-search-content">

                <div class="search-input">
                    <form class="d-flex" method="get" action="{% url 'modulo:BooksPage' %}">
                        <button type="submit">
                            <img src="{%static 'icons/search.svg'%}">
                        </button>
                        <input type="search" placeholder="Buscar Libro" aria-label="Search" name="buscar"
                            value="{{ request.GET.buscar }}">
                    </form>
                </div>

            </div>

        </div>

        <div class="navbar-icons">
            <div class="book-cart-icon">
                <img src="{%static 'icons/library.svg'%}">
            </div>
            <div class="user-icon">
                <img src="{%static 'icons/user1.svg'%}">
            </div>
        </div>

    </nav>
</body>

</html>

Aplicaciones/Modulo/templates/adminBookDetail.html
{% extends "index.html" %}
{% load static %}

{% block title %} Biblioteca Politecnica Libros {% endblock %}

{% block content %}
{% include "BarraNavegacionAdmin.html" %}

<div class=bookDetail">
    <div class="book-detail-content">

        <div class="book-detail-card">
            <form method="POST" enctype="multipart/form-data" class="book-detail-form">
                {% csrf_token %}
                <div class="book-detail-image book-detail-image-admin">
                    <div class="book-detail-image-content-admin">
                        <img src="{{ book.imagen.url }}">
                        <div class="book-detail-image-cover">
                            <div class="book-detail-image-cover-content">
                                <div class="book-detail-button-edit-image">
                                    {{ book_form.imagen}}
                                </div>
                                <button type="button" onclick="document.getElementById('id_imagen').click()">Cambiar
                                    Imagen</button>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="book-detail-description book-detail-description-admin">
                    <div class="book-detail-info book-detail-info-admin">
                        <div class="book-detail-title book-detail-admin">
                            <p>Titulo: </p>{{ book_form.titulo }}
                        </div>
                        <div class="book-detail-id book-detail-admin">
                            <p>Código Interno: </p>{{ book_form.codigo_interno }}
                        </div>
                        <div class="book-detail-available book-detail-admin">
                            <p>Disponibles: </p>{{ book_form.disponibles }}
                        </div>
                        <p class="text-informacion-del-libro">Informacion del libro</p>
                        <div class="book-detail-status book-detail-admin">
                            <p>Estado: </p>{{ book_form.estado_libro }}
                        </div>
                        <div class="book-detail-author book-detail-admin">
                            <p>Autor: </p>{{ book_form.autor }}
                        </div>
                        <div class="book-detail-editorial book-detail-admin">
                            <p>Editorial: </p>{{ book_form.editorial }}
                        </div>
                        <div class="book-detail-languague book-detail-admin">
                            <p>Idioma: </p>{{ book_form.idioma }}
                        </div>
                        <div class="book-detail-pages book-detail-admin">
                            <p>Paginas: </p>{{ book_form.paginas }}
                        </div>
                        <div class="book-detail-career book-detail-admin">
                            <p>Carrera: </p>{{ book_form.carrera }}
                        </div>
                    </div>
                    <div class="book-detail-buttons">
                        <div class="button-content boton-guardar">
                            <button type="submit" class="primary-button button-guardar">Guardar Cambios</button>
                        </div>
                        <div class="button-content boton-Eliminar">
                            <a href="{% url 'modulo:AdminDeleteBook' book.codigo_interno %}">
                                <div class="button-content boton-eliminar">
                                    <button type="button" class="primary-button button-Eliminar">Eliminar Libro</button>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


{% include "footer.html" %}
{% endblock %}

Aplicaciones/Modulo/templates/adminBooksPage.html
{% extends "index.html" %}
{% load static %}

{% block title %} Biblioteca Politecnica Libros {% endblock %}

{% block content %}
{% include "BarraNavegacionAdmin.html" %}
<div class="Biblioteca">

    <div class="content-alert">
        {% if messages%}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-success" role="alert">
                <li{% if message.tag %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
            </div>
            {% endfor%}
        </ul>
        {% endif%}
    </div>

    <div class="add-career-page inactive">
        {% include "adminAddCareer.html" %}
    </div>
    
    <div class="add-charge-page inactive">
        {% include "adminAddCharge.html" %}
    </div>

    <div class="add-shift-page inactive">
        {% include "adminAddShift.html" %}
    </div>

    <div class="add-user-page inactive">
        {% include "adminAddUser.html" %}
    </div>

    <div class="aside-user-menu-admin inactive">
        {% include "userMenu.html" %}
    </div>

    <nav class="secondary-navbar">

        <div class="secondary-navbar-content">

            <div class="secondary-navbar-sections">
                <a href="#Ingeniería Agroindustrial">
                    <p>Agroindustrial</p>
                </a>
                <a href="#Ingeniería en Tecnología Ambiental">
                    <p>Ambiental</p>
                </a>
                <a href="#Ingeniería en Animación y Efectos Visuales">
                    <p>Animación</p>
                </a>
                <a href="#Ingeniería en Sistemas Automotrices">
                    <p>Automotrices</p>
                </a>
                <a href="#Ingeniería en Energía">
                    <p>Energía</p>
                </a>
                <a href="#Ingeniería Financiera">
                    <p>Financiera</p>
                </a>
                <a href="#Ingeniería en Logística y Transporte">
                    <p>Logística</p>
                </a>
                <a href="#Ingeniería Mecatrónica">
                    <p>Mecatrónica</p>
                </a>
                <a href="#Ingeniería en Nanotecnología">
                    <p>Nanotecnología</p>
                </a>
                <a href="#Ingeniería en Software">
                    <p>Software</p>
                </a>
            </div>

        </div>

    </nav>

    <div class="books-page">
        {% for carrera in carreras %}
        <div class="list-books" id="{{ carrera.nom_carrera }}">

            <div class="section-name">
                <h1>{{ carrera.nom_carrera }}</h1>
            </div>

            <div class="list-books-section">
                <div class="list-books-container">
                    <img class="control prev" src="{%static 'images/left.png'%}" alt="">
                    <div class="slider">
                        {% for libro in libros %}
                        {% if libro.carrera == carrera %}
                        <div class="book admin-book">
                            <div class="book-content">

                                <div class="book-image">
                                    <div class="image-content">
                                        <img src="{{libro.imagen.url}}">
                                    </div>
                                    <div class="edit-icon">
                                        <a href="{% url 'modulo:AdminBookDetail' libro.codigo_interno %}">
                                            <img src="{%static 'icons/edit.svg'%}">
                                        </a>
                                    </div>
                                </div>

                                <div class="book-description">
                                    <div class="book-info">
                                        <div class="book-title">
                                            <p>{{ libro.titulo }}</p>
                                        </div>

                                        <div class="book-author">
                                            <p>Autor: {{ libro.autor }}</p>
                                        </div>

                                        <div class="book-available">
                                            <p>Disponibles: {{ libro.disponibles }}</p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <img class="control next" src="{%static 'images/right.png'%}" alt="">
                </div>
            </div>

        </div>
        {% endfor%}

    </div>
</div>
<script>
    /*Programacion Slider*/ 
    const slider = document.getElementsByClassName('slider')
    const prev = document.getElementsByClassName('prev')
    const next = document.getElementsByClassName('next')

    for (let index = 0; index < slider.length; index++) {
        prev[index].addEventListener('click', () => (
            slider[index].scrollLeft -= 600))
        next[index].addEventListener('click', () => (
            slider[index].scrollLeft += 600))
        console.log(prev)
        console.log(next)
    }
    /*Programacion menu de vistas de la pagina de libros*/
    const buttonAddUser = document.querySelector('.add-user-icon')
    const buttonAddCareer = document.querySelector('.add-career-icon')
    const buttonAddCharge = document.querySelector('.add-charge-icon')
    const buttonAddShift = document.querySelector('.add-shift-icon')
    const buttonAdminMenu = document.querySelector('.admin-icon')
    const addUserPage = document.querySelector('.add-user-page')
    const addCareerPage = document.querySelector('.add-career-page')
    const addChargePage = document.querySelector('.add-charge-page')
    const addShiftPage = document.querySelector('.add-shift-page')
    const AdminMenu = document.querySelector('.aside-user-menu-admin')

    buttonAdminMenu.addEventListener('click', toggleAdminMenu)
    buttonAddUser.addEventListener('click', toggleUserPage)
    buttonAddCareer.addEventListener('click', toggleCareerPage)
    buttonAddCharge.addEventListener('click', toggleChargePage)
    buttonAddShift.addEventListener('click', toggleShiftPage)

    function toggleUserPage() {
        addUserPage.classList.toggle('inactive');
    }

    function toggleAdminMenu() {
        AdminMenu.classList.toggle('inactive')
    }

    function toggleCareerPage() {
        addCareerPage.classList.toggle('inactive')
    }

    function toggleChargePage() {
        addChargePage.classList.toggle('inactive')
    }

    function toggleShiftPage() {
        addShiftPage.classList.toggle('inactive')
    }
</script>
{% include "footer.html" %}
{% endblock %}

Aplicaciones/Modulo/templates/adminRequestList.html
{% extends "index.html" %}
{% load static %}

{% block title %} Biblioteca Politecnica Libros {% endblock %}

{% block content %}
{% include "BarraNavegacionAdmin.html" %}
<div class="adminRequestList">
    <div class="admin-request-list-content">

        <div class="admin-request-list-up">
            <div class="admin-request-list-title">
                <div class="admin-request-list-title-content">
                    <p>Prestamos</p>
                </div>
            </div>
            <div class="admin-request-list-search">
                <div class="admin-request-list-search-content">

                    <div class="search-input">
                        <form class="d-flex" method="get" action="{% url 'modulo:AdminRequestList' %}">
                            <button type="submit">
                                <img src="{%static 'icons/search.svg'%}">
                            </button>
                            <input type="search" placeholder="Buscar Prestamo" aria-label="Search" name="buscar"
                                value="{{ request.GET.buscar }}">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin-request-list-body">
            <div class="admin-request-list-table">
                <table>
                    <thead>
                        <tr class="admin-request-list-table-titles">
                            <th class="table-title">
                                <p>No. de préstamo</p>
                            </th>
                            <th class="table-title">
                                <p>Libros</p>
                            </th>
                            <th class="table-title">
                                <p>Prestatario</p>
                            </th>
                            <th class="table-title">
                                <p>Fecha de devolución</p>
                            </th>
                            <th class="table-title">
                                <p>Estado</p>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for prestamo in prestamos %}
                        {% for det_prestamo in det_prestamos %}
                        {% if det_prestamo.id_prestamo == prestamo %}
                        <tr class="request">
                            <td class="request-data id">
                                <p>#P{{ prestamo.id_prestamo }}</p>
                            </td>
                            <td class="request-data libros">
                                <p>{{ det_prestamo.libro }}</p>
                            </td>
                            <td class="request-data prestatario">
                                <p>{{ prestamo.id_usuario }}</p>
                            </td>
                            <td class="request-data fecha-devolucion">
                                <p>{{ prestamo.fecha_devolucion }}</p>
                            </td>
                            <td class="request-data estado">
                                <p>{{ det_prestamo.estatus }}</p>
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% include "footer.html" %}
{% endblock %}

Aplicaciones/Modulo/templates/bookDetail.html
{% extends "index.html" %}
{% load static %}

{% block title %} Biblioteca Politecnica Libros {% endblock %}

{% block content %}
{% include "BarraNavegacion.html" %}

<div class=bookDetail">
    <div class="book-detail-content">

        <div class="book-detail-card">
            <div class="book-detail-image">
                <div class="book-detail-image-content">
                    <img src="{{book.imagen.url}}">
                </div>
            </div>
            <div class="book-detail-description">
                <div class="book-detail-info">
                    <div class="book-detail-title">
                        <p>{{ book.titulo }}</p>
                    </div>
                    <div class="book-detail-available">
                        <p>Disponibles: {{ book.disponibles }}</p>
                    </div>
                    <p class="text-informacion-del-libro">Información del libro</p>
                    <div class="book-detail-author">
                        <p>Autor: {{ book.autor }}</p>
                    </div>
                    <div class="book-detail-editorial">
                        <p>Editorial: {{ book.editorial }}</p>
                    </div>
                    <div class="book-detail-languague">
                        <p>Idioma: {{ book.idioma }}</p>
                    </div>
                    <div class="book-detail-pages">
                        <p>Paginas: {{ book.paginas }}</p>
                    </div>
                </div>
                <div class="book-detail-buttons">
                    <div class="button-content boton-solicitar">
                        <a href="{% url 'modulo:BookRequest' book.codigo_interno %}">
                            <button class="primary-button button-solicitar">Solicitar</button>
                        </a>
                    </div>
                    <div class="button-content boton-Añadir">
                        <a href="#">
                            <button type="submit" class="primary-button button-Añadir">Añadir al librero</button>
                        </a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% include "footer.html" %}
{% endblock %}